version: "3.3"

volumes:
  postgres_data:


services:
  db:
    image: postgres:13.0-alpine
    container_name: testtask-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: testtask-backend
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn test_task_elros.wsgi:application --bind 0.0.0.0:8000"

  nginx:
      image: nginx:latest
      container_name: testtask-nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      restart: always